//2: Stadium Seating
#include <iostream>
#include <iomanip>

using namespace std;
int main()
{
	double seatA, seatB, seatC, total;
	const double rateA = 15, rateB = 12, rateC = 9;
	cout << "Please input the number of Class A seats sold: ";
	cin >> seatA;
	cout << "Please input the number of Class B seats sold: ";
	cin >> seatB;
	cout << "Please input the number of Class C seats sold: ";
	cin >> seatC;
	total = seatA*rateA + seatB*rateB + seatC*rateC;
	cout << setprecision(2) << fixed;
	cout << "The amount of income generated by ticket sale is: $" << total << endl;
	return 0;
}